### PR TITLE
quick searchable dropdown list from menubar

### PR DESCRIPTION
**Pull request by effervescentia**

### CODE REVIEW

**Comment by ragingwind** [comment]
Thanks for PR but Could you please don't mess up indent and coding style. Keep imports(require) order and Remove logs

**Comment by effervescentia** [comment]
Hey, I updated some of the places where your inlined code was broken out by my auto-formatter. As for the indent style I'm using your .editorconfig file, if you want me to follow a different code style please edit that file and my formatter will work accordingly. With regards to the imports, what order do you want to be used?

**Comment by ragingwind** [comment]
@effervescentia I've just tested with your PR. It's a little bit different to my purpose that I've concerned. but It would be one of great way to use devdocs so I would recommend you make new one

**Comment by effervescentia** [comment]
Fair enough :P will do

**Comment by ragingwind** [comment]
@effervescentia Thanks for understanding.

**Pull request closed without merging**
